// Generated by scripts/gen-firebase-config.js — do not edit by hand.
globalThis.FIREBASE_CONFIG = {
  "apiKey": "AIzaSyC8bwT0HedkosTVqnVDQ5ChmyO-ZMl7AQ4",
  "authDomain": "autoform-46257.firebaseapp.com",
  "projectId": "autoform-46257",
  "storageBucket": "autoform-46257.firebasestorage.app",
  "messagingSenderId": "293004209821",
  "appId": "1:293004209821:web:0fadbaad7a28f538566e74",
  "measurementId": "G-HBFW7JR9DD",
  "databaseURL": "https://autoform-46257-default-rtdb.europe-west1.firebasedatabase.app"
};
globalThis.FIREBASE_CONFIG_AVAILABLE = true;
